# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 39, 561, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.process_vid = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.process_vid.setObjectName("process_vid")
        self.verticalLayout_8.addWidget(self.process_vid)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.control_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.control_btn.setObjectName("control_btn")
        self.verticalLayout.addWidget(self.control_btn)
        self.file_load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.file_load_btn.setGeometry(QtCore.QRect(10, 0, 75, 23))
        self.file_load_btn.setObjectName("file_load_btn")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.process_vid.setText(_translate("MainWindow", "TextLabel"))
        self.control_btn.setText(_translate("MainWindow", "Start"))
        self.file_load_btn.setText(_translate("MainWindow", "Load File"))

