# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(826, 457)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 130))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 130))
        self.groupBox.setObjectName("groupBox")
        self.file_load_btn = QtWidgets.QPushButton(self.groupBox)
        self.file_load_btn.setGeometry(QtCore.QRect(10, 20, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_load_btn.sizePolicy().hasHeightForWidth())
        self.file_load_btn.setSizePolicy(sizePolicy)
        self.file_load_btn.setObjectName("file_load_btn")
        self.car_label = QtWidgets.QLabel(self.groupBox)
        self.car_label.setGeometry(QtCore.QRect(20, 60, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.car_label.setFont(font)
        self.car_label.setObjectName("car_label")
        self.car_count = QtWidgets.QLabel(self.groupBox)
        self.car_count.setGeometry(QtCore.QRect(110, 60, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.car_count.setFont(font)
        self.car_count.setObjectName("car_count")
        self.motor_label = QtWidgets.QLabel(self.groupBox)
        self.motor_label.setGeometry(QtCore.QRect(20, 90, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.motor_label.setFont(font)
        self.motor_label.setObjectName("motor_label")
        self.motor_count = QtWidgets.QLabel(self.groupBox)
        self.motor_count.setGeometry(QtCore.QRect(110, 90, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.motor_count.setFont(font)
        self.motor_count.setObjectName("motor_count")
        self.verticalLayout.addWidget(self.groupBox)
        self.process_vid = QtWidgets.QLabel(Form)
        self.process_vid.setObjectName("process_vid")
        self.verticalLayout.addWidget(self.process_vid)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Vehicle Counting"))
        self.groupBox.setTitle(_translate("Form", "Panel"))
        self.file_load_btn.setText(_translate("Form", "Load File"))
        self.car_label.setText(_translate("Form", "Car:"))
        self.car_count.setText(_translate("Form", "0"))
        self.motor_label.setText(_translate("Form", "Motor:"))
        self.motor_count.setText(_translate("Form", "0"))
        self.process_vid.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
